### ISSUE TITLE
The conda install of hydromt seems to be broken

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#1041]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

``` 
> mamba create -n test-env -c conda-forge hydromt
> hydromt --models

```

### Current behaviour

```
Traceback (most recent call last):
  File "C:\Users\boisgont\AppData\Local\miniforge3\envs\test-env\Scripts\hydromt-script.py", line 5, in <module>
    from hydromt.cli.main import main
  File "C:\Users\boisgont\AppData\Local\miniforge3\envs\test-env\Lib\site-packages\hydromt\__init__.py", line 18, in <module>
    from . import cli, gis, stats, workflows
  File "C:\Users\boisgont\AppData\Local\miniforge3\envs\test-env\Lib\site-packages\hydromt\gis\__init__.py", line 3, in <module>
    from .merge import merge
  File "C:\Users\boisgont\AppData\Local\miniforge3\envs\test-env\Lib\site-packages\hydromt\gis\merge.py", line 6, in <module>
    from hydromt.gis.raster import full_from_transform
  File "C:\Users\boisgont\AppData\Local\miniforge3\envs\test-env\Lib\site-packages\hydromt\gis\raster.py", line 44, in <module>
    from hydromt.gis import utils
  File "C:\Users\boisgont\AppData\Local\miniforge3\envs\test-env\Lib\site-packages\hydromt\gis\utils.py", line 17, in <module>
    from pyogrio import read_info
  File "C:\Users\boisgont\AppData\Local\miniforge3\envs\test-env\Lib\site-packages\pyogrio\__init__.py", line 9, in <module>
    from pyogrio.core import (
  File "C:\Users\boisgont\AppData\Local\miniforge3\envs\test-env\Lib\site-packages\pyogrio\core.py", line 24, in <module>
    from pyogrio._io import ogr_list_layers, ogr_read_bounds, ogr_read_info
ImportError: DLL load failed while importing _io: The specified procedure could not be found.
```

### Desired behaviour

Installation should work again.

### Additional context

Tested with python 3.12 and 3.11
Installing hydromt 0.9.4 seems to work though: mamba create -n test-env -c conda-forge hydromt=0.9.4 python=3.11

**Comment by savente93** [comment]
issue no longer reproduces, and there have been some conda releases in the mean time so I'm assuming this is fixed now.
