### ISSUE TITLE
hydromt update forcing crashes often

### ISSUE THREAD

**Issue by ahweerts** [Deltares/hydromt#254]
I get an 

I get this error a lot

2022-12-11 18:54:16,002 - update - wflow - INFO - Write forcing file
2022-12-11 18:54:16,043 - update - wflow - INFO - Process forcing; saving to C:\wflow_julia\Orange\inmaps-era5-1967-2022.nc
2022-12-11 18:56:39,281 - update - main - ERROR - [Errno 22] Invalid argument
Traceback (most recent call last):
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\hydromt\cli\main.py", line 275, in update
    mod.update(model_out=model_out, opt=opt)
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\hydromt\models\model_api.py", line 295, in update
    self.write()
  File "C:\hydromt_wflow\hydromt_wflow\wflow.py", line 1613, in write
    self.write_forcing()
  File "C:\hydromt_wflow\hydromt_wflow\wflow.py", line 1944, in write_forcing
    delayed_obj.compute(**kwargs)
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\base.py", line 315, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\base.py", line 600, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\threaded.py", line 89, in get
    results = get_async(
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\local.py", line 319, in reraise
    raise exc
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\core.py", line 149, in get
    result = _execute_task(task, cache)
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\dask\array\core.py", line 126, in getter
    c = np.asarray(c)
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\xarray\core\indexing.py", line 459, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\xarray\core\indexing.py", line 623, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\xarray\core\indexing.py", line 524, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\xarray\backends\zarr.py", line 68, in __getitem__
    return array[key.tuple]
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\zarr\core.py", line 807, in __getitem__
    result = self.get_basic_selection(pure_selection, fields=fields)
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\zarr\core.py", line 933, in get_basic_selection
    return self._get_basic_selection_nd(selection=selection, out=out,
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\zarr\core.py", line 976, in _get_basic_selection_nd
    return self._get_selection(indexer=indexer, out=out, fields=fields)
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\zarr\core.py", line 1267, in _get_selection
    self._chunk_getitem(chunk_coords, chunk_selection, out, out_selection,
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\zarr\core.py", line 1966, in _chunk_getitem
    cdata = self.chunk_store[ckey]
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\zarr\storage.py", line 1072, in __getitem__
    return self._fromfile(filepath)
  File "C:\Users\weerts\Anaconda3\envs\hydromt-wflow\lib\site-packages\zarr\storage.py", line 1047, in _fromfile
    return f.read()
OSError: [Errno 22] Invalid argument

**Comment by hboisgon** [comment]
Close for now, no news and I guess connection problem?
