### ISSUE TITLE
BUG: _uri_validator called with Path object in DataCatalog

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#413]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

Happens when calling data_catalog.from_dict() (might be easier to reproduce than below)

```
# data_libs_like in zip folder below
source_like='era5'
fns = ["experience/realization_1/rlz_1_cst_1.nc", ...]

data_catalog = hydromt.DataCatalog(data_libs=data_libs_like)
dc_like = data_catalog[source_like].to_dict()

climate_data_catalog = hydromt.DataCatalog()
climate_data_dict = dict()

for fn in fns:
    fn = Path(fn, resolve_path=True)
    name = os.path.basename(fn).split(".")[0]
    dc_fn = dc_like.copy()
    dc_fn["path"] = fn
    if "kwargs" not in dc_fn:
        dc_fn["kwargs"] = dict()
    dc_fn["kwargs"]["preprocess"] = "transpose_dims"
    dc_fn["meta"][
        "processing"
    ] = f"Climate data generated from {source_like} using Deltares/weathergenr"
    # remove entries that have already been processed while reading in the data:
    for v in ["unit_mult", "unit_add", "rename"]:
        if v in dc_fn:
            dc_fn.pop(v)
    climate_data_dict[name] = dc_fn

climate_data_catalog.from_dict(climate_data_dict)
```

### Current behaviour

Throws error

```
Traceback (most recent call last):
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\data_adapter\caching.py", line 25, in _uri_validator
    result = urlparse(uri)
  File "C:\Users\boisgont\Miniconda3\envs\blueearth-cst\lib\urllib\parse.py", line 391, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "C:\Users\boisgont\Miniconda3\envs\blueearth-cst\lib\urllib\parse.py", line 128, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "C:\Users\boisgont\Miniconda3\envs\blueearth-cst\lib\urllib\parse.py", line 112, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "C:\Users\boisgont\Miniconda3\envs\blueearth-cst\lib\urllib\parse.py", line 112, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'WindowsPath' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\boisgont\D\Repos\CST\blueearth_cst\.snakemake\scripts\tmpts2t778n.prepare_climate_data_catalog.py", line 106, in <module>
    _ = prepare_clim_data_catalog(
  File "C:\Users\boisgont\D\Repos\CST\blueearth_cst\.snakemake\scripts\tmpts2t778n.prepare_climate_data_catalog.py", line 101, in prepare_clim_data_catalog
    climate_data_catalog.from_dict(climate_data_dict)
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\data_catalog.py", line 395, in from_dict
    data_dict = _parse_data_dict(
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\data_catalog.py", line 970, in _parse_data_dict
    if not _uri_validator(path):
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\data_adapter\caching.py", line 27, in _uri_validator
    except ValueError | AttributeError:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

### Desired behaviour

Should not throw error (this used to work)

### Additional context

[climate_data_catalog.zip](https://github.com/Deltares/hydromt/files/11796324/climate_data_catalog.zip)

**Comment by DirkEilander** [comment]
# Issue
`_uri_validator` is called with pathlib.Path, while it only recognises string paths
This occurs in https://github.com/Deltares/hydromt/blob/0144d5dadfb76a9f2bdb22226b484e83c9751c34/hydromt/data_catalog.py#L970

# minimal reproducible example

```python
import hydromt
from pathlib import Path

cat = hydromt.DataCatalog()
fn = Path("foo.nc", resolve_path=True)

data_dict = {'foo': {
    'data_type': 'RasterDataset', 
    'path': fn, 
    }
}

cat.from_dict(data_dict)
```

# solution

make sure `_uri_validator` is always called with a string

**Comment by savente93** [comment]
Would it be good to add your minimal reproducible example as a test?
