### ISSUE TITLE
Pilot of improved support for cloud data 

### ISSUE THREAD

**Issue by alimeshgi** [Deltares/hydromt#416]
### Kind of request

Adding new functionality

### Enhancement Description
For the pilot of cloud data we want to investigate the following:
- [x] Choose subset of data for the pilot. This subset should be sufficient to build a full model (Dirk) 
- [x] Choosing a cloud provider (Floris/jaap) #430 
- [x] Get a go of DT team to do the pilot, also in terms of finance (Ali) 
- [x] Inventorize what format the data is currently in and whether we can optimize this? (me)
- [x] Compare speed of cloud provider to P drive (me) 
- [ ] Do we want to phase out P drive? what are the trade offs (me)

### Use case
Before we start moving everything to the cloud we want to do some prep work to make sure we know what we're going into, hence this pilot. This will also give us better insight into costs and performance. 

### Additional Context

This should probably be split into several different issues, but these are at least these are descriptions of necessary actions.

**Comment by DirkEilander** [comment]
I suggest to select a subset of deltares_data catalog which is required to setup a typical wflow model:
- merit_hydro_ihu
- merit_hydro_ihu_index
- rivers_lin2019_v1
- hydro_reservoirs
- hydro_lakes
- rgi
- vito
- modis_lai
- soilgrids
- grdc
- era5 (if possible use ERA5 hosted on GS, see #296)
- era5_orography

**Comment by savente93** [comment]
We've made a good start on the could pilot yesterday. Jaap is currently in charge of gathering the final results, so for the time being I've assigned him

**Comment by DirkEilander** [comment]
Keep in mind that for some of the files we will need to transform the data to cloud optimized format for a fair comparison / to improve performance both for local and cloud files. 
To my knowledge these are possible cloud optimized file formats
- vector data: flatgeobuf (tool ogr2ogr) / recently geoparquet is also being used and supported by gdal
- raster data (2D): cloud optimized geotiff COG (tool [rio-cogeo](https://github.com/cogeotiff/rio-cogeo))
- raster data (3D): zarr
- tabular data: parquet

questions to answer: are COG tiles with vrt also performant or is one large COG preferable

**Comment by Jaapel** [comment]
The location of the cloud pilot's code is here: https://github.com/Jaapel/wflow-cloud-pilot/
 
In short we created:
- an upload script for the data for the example wflow workflow as mentioned in the docs.
- monitoring scripts to monitor network usage around the workflow
- a notebook to analyse those results
We also:
- did some bugfixes for hydromt-core to allow all things to work.
- patched hydromt-wflow [here](https://github.com/Deltares/hydromt_wflow/tree/implement_nodata) to work with these changes

The workflow now can start running but still fails due to xarray having some difficulty opening datasets on s3:
```log
syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: <?xml^ version="1.0" encoding="UTF-8"?><Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Endpoint>hydromt-data.s3.eu-central-1.amazonaws.com</Endpoint><Bucket>hydromt-data</Bucket><RequestId>W49JMHNK7S83REE0</RequestId><HostId>PcWCJErtOekvP/Jn/nWvnRZrrx+I8a5LDYorUv2MBPqIDuPh/vpoWpxTaJCPdC+95XWmWqYHe8s=</HostId></Error>
Traceback (most recent call last):
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
           ~~~~~~~~~~~^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
            ~~~~~~~~~~~^^^^^
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('s3://hydromt-data/meteo/era5_daily/nc_merged/era5_2010_daily.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '085ff635-b831-47eb-b7a1-d3ab97817898']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaapel/miniforge3/envs/hydromtcp/bin/hydromt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/hydromt/cli/main.py", line 207, in build
    mod.build(region, opt=opt)
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/hydromt/models/model_api.py", line 240, in build
    self._run_log_method(method, **kwargs)
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/hydromt/models/model_api.py", line 182, in _run_log_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/hydromt_wflow/wflow.py", line 2062, in setup_precip_forcing
    precip = self.data_catalog.get_rasterdataset(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/hydromt/data_catalog.py", line 1328, in get_rasterdataset
    obj = source.get_data(
          ^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/hydromt/data_adapter/rasterdataset.py", line 290, in get_data
    ds = self._read_data(fns, geom, bbox, cache_root, zoom_level, logger)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/hydromt/data_adapter/rasterdataset.py", line 336, in _read_data
    ds = xr.open_mfdataset(fns, decode_coords="all", **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/xarray/backends/api.py", line 1035, in open_mfdataset
    datasets, closers = dask.compute(datasets, closers)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/dask/base.py", line 628, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/xarray/backends/api.py", line 573, in open_dataset
    backend_ds = backend.open_dataset(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/xarray/backends/netCDF4_.py", line 603, in open_dataset
    store = NetCDF4DataStore.open(
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/xarray/backends/netCDF4_.py", line 400, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/xarray/backends/netCDF4_.py", line 347, in __init__
    self.format = self.ds.data_model
                  ^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/xarray/backends/netCDF4_.py", line 409, in ds
    return self._acquire()
           ^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/xarray/backends/netCDF4_.py", line 403, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaapel/miniforge3/envs/hydromtcp/lib/python3.11/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/netCDF4/_netCDF4.pyx", line 2464, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2027, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -72] NetCDF: Malformed or inaccessible DAP2 DDS or DAP4 DMR response: 's3://hydromt-data/meteo/era5_daily/nc_merged/era5_2010_daily.nc'
```

**Comment by savente93** [comment]
decided during standup: make cloud optimised replicas of the data

**Comment by Jaapel** [comment]
First results using the era5 zarr:
Network usage for Gabon
![aws_small](https://github.com/Deltares/hydromt/assets/33715902/b79e3780-c80c-45cf-ae4b-dacd0fabcfa1)
vs the Rhine Basin
![aws_large](https://github.com/Deltares/hydromt/assets/33715902/7d9fbc96-4255-4950-9edd-f90668ae88ec)

Of course, just using 3 months of data, but still :)
Now we can perhaps compare minio. This was from my home network

**Comment by Jaapel** [comment]
Small via Deltares Minio
![minio_small](https://github.com/Deltares/hydromt/assets/33715902/d8cc415c-2e6c-43ce-a02f-e47e18c4978b)
Large via Deltares Minio
![minio_large](https://github.com/Deltares/hydromt/assets/33715902/5ed4a4ae-6a84-4204-a84e-548def150e52)

**Comment by savente93** [comment]
One question we would have to still answer that would be involved if we want to think about phasing out the p drive is how well MinIO performs inside the deltares and whether that has feature parity and/or cost considerations that may or may not be there right now. We'd have to know more about the usage statistics inside deltares to make a fair comparison but I don't expect this to result in a different conclusion. I think the provenance and security benefits are already worth it.

**Comment by savente93** [comment]
It is difficult to accurately compare the pictures because of the different axis. do you still have the data files? if so I'd like to look at them. Regardless, this is clear enough that we can call this complete and we simply need to talk about next steps with the team. The quarterly planning will be a good moment for this. I'll be closing this as completed now, but feel free to reopen if necessary. It would be good if we sit together and perhaps come up with a conclusion presentation when you are back in the office
