### ISSUE TITLE
Current yaml format pre-commit hook does not work on windows

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#426]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

Add-Content .\data\catalog\deltares_data.yml `n
git add .
git commit -m "should fail on ymlfmt" 

### Current behaviour

Underwindows (PS specifically, but also unde CMD) the current yaml format hook does not work. Apparently it is a known issue that this hook does not work on windows. 

### Desired behaviour

We should either decide to just not have the hook or find one that does work on windows 

### Additional context

thanks for @Tjalling-dejong for flagging this

**Comment by DirkEilander** [comment]
I still get an error with the google pre-commit hook. Had to comment it out in #434 
Any clues @savente93? 

There are more yml alternatives written in python instead of go, such as https://github.com/adrienverge/yamllint
Also, I'm happy with just having the standard check-yaml hook.

### version information

```
pre-commit version: 3.3.3
git --version: git version 2.34.1.windows.1
sys.version:
    3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:14:58) [MSC v.1929 64 bit (AMD64)]
sys.executable: C:\Users\eilan_dk\Miniconda3\envs\hydromt-dev\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\eilan_dk\\.cache\\pre-commit\\repo83m0hcsp\\golangenv-default\\.go\\bin\\go.EXE', 'install', './...')
return code: 1
stdout: (none)
stderr:
    go: downloading github.com/braydonk/yaml v0.5.0
    go: downloading github.com/mitchellh/mapstructure v1.5.0
    go: downloading github.com/RageCage64/multilinediff v0.2.0
    go: downloading github.com/bmatcuk/doublestar/v4 v4.6.0
    go: downloading github.com/google/go-cmp v0.5.9
    error obtaining VCS status: exit status 128
    	Use -buildvcs=false to disable VCS stamping.
```

```
Traceback (most recent call last):
  File "C:\Users\eilan_dk\Miniconda3\envs\hydromt-dev\lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Users\eilan_dk\Miniconda3\envs\hydromt-dev\lib\site-packages\pre_commit\main.py", line 386, in main
    return hook_impl(
  File "C:\Users\eilan_dk\Miniconda3\envs\hydromt-dev\lib\site-packages\pre_commit\commands\hook_impl.py", line 271, in hook_impl
    return retv | run(config, store, ns)
  File "C:\Users\eilan_dk\Miniconda3\envs\hydromt-dev\lib\site-packages\pre_commit\commands\run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "C:\Users\eilan_dk\Miniconda3\envs\hydromt-dev\lib\site-packages\pre_commit\repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\eilan_dk\Miniconda3\envs\hydromt-dev\lib\site-packages\pre_commit\repository.py", line 95, in _hook_install
    lang.install_environment(
  File "C:\Users\eilan_dk\Miniconda3\envs\hydromt-dev\lib\site-packages\pre_commit\languages\golang.py", line 152, in install_environment
    lang_base.setup_cmd(prefix, ('go', 'install', './...'), env=env)
  File "C:\Users\eilan_dk\Miniconda3\envs\hydromt-dev\lib\site-packages\pre_commit\lang_base.py", line 86, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "C:\Users\eilan_dk\Miniconda3\envs\hydromt-dev\lib\site-packages\pre_commit\util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\eilan_dk\\.cache\\pre-commit\\repo83m0hcsp\\golangenv-default\\.go\\bin\\go.EXE', 'install', './...')
return code: 1
stdout: (none)
stderr:
    go: downloading github.com/braydonk/yaml v0.5.0
    go: downloading github.com/mitchellh/mapstructure v1.5.0
    go: downloading github.com/RageCage64/multilinediff v0.2.0
    go: downloading github.com/bmatcuk/doublestar/v4 v4.6.0
    go: downloading github.com/google/go-cmp v0.5.9
    error obtaining VCS status: exit status 128
    	Use -buildvcs=false to disable VCS stamping.
```

**Comment by savente93** [comment]
what medium are you using? CMD, PS or Vscode?

**Comment by savente93** [comment]
I'll be honest. I have no idea. 

> Also, I'm happy with just having the standard check-yaml hook. 
Let's just remove it then, you can do that in the PR you referenced imo
