### ISSUE TITLE
Bug updating attrs in get_data method

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#677]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

The issue happens if you have several variables in one dataset (eg precip, temp etc.) but when calling get_rasterdataset(variables=["precip"]) to select only specific variables, setting attrs fails.

In my example, I have this data source:
```
wflow_sbm_output:
  path: run_delwaq/output.nc
  crs: 4326
  data_type: RasterDataset
  driver: netcdf
  kwargs:
    chunks:
      lat: 500
      lon: 500
      time: -1
    preprocess: harmonise_dims
  meta:
    category: hydro
  rename:
    q_river: discharge
    vol_river: volume
  attrs:
    discharge:
      unit: m3/s
    volume:
      unit: m3
```

And when trying to read with get_rasterdataset(variables=['volume']), I get a key error message:

```
Traceback (most recent call last):
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-delwaq\Lib\site-packages\hydromt\cli\main.py", line 226, in build
    mod.build(region, opt=opt)
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-delwaq\Lib\site-packages\hydromt\models\model_api.py", line 236, in build
    self._run_log_method(method, **kwargs)
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-delwaq\Lib\site-packages\hydromt\models\model_api.py", line 178, in _run_log_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\SnapVolumesTemp\MountPoints\{45c63495-0000-0000-0000-100000000000}\{2321B4C4-0175-42EB-9400-1984F45E98CF}\SVROOT\Users\boisgont\Documents\Repos\hydromt_delwaq\hydromt_delwaq\delwaq.py", line 428, in setup_flooding
    da_v = self.data_catalog.get_rasterdataset(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-delwaq\Lib\site-packages\hydromt\data_catalog.py", line 1378, in get_rasterdataset
    obj = source.get_data(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-delwaq\Lib\site-packages\hydromt\data_adapter\rasterdataset.py", line 305, in get_data
    ds = self._set_metadata(ds)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-delwaq\Lib\site-packages\hydromt\data_adapter\rasterdataset.py", line 593, in _set_metadata
    ds[k].attrs.update(self.attrs[k])
    ~~^^^
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-delwaq\Lib\site-packages\xarray\core\dataset.py", line 1544, in __getitem__
    return self._construct_dataarray(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-delwaq\Lib\site-packages\xarray\core\dataset.py", line 1448, in _construct_dataarray
    _, name, variable = _get_virtual_variable(self._variables, name, self.dims)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-delwaq\Lib\site-packages\xarray\core\dataset.py", line 214, in _get_virtual_variable
    raise KeyError(key)
KeyError: 'discharge'
```

### Current behaviour

Fails (see above).

### Desired behaviour

Should not fail and raise a KeyError.

### Additional context

Apparently there is no issues for renaming but good to double check if this happens with other processes like unit_mult or unit_add.
Check also if this is present for other DataAdapters and not just RasterDataset

**Comment by savente93** [comment]
Fixed in #1117
