### ISSUE TITLE
Bug: Read shapefiles with get_geodataframe and a mask

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#691]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

Reading a shapefile and filtering with a mask (geom is not None). I can provide a shapefile if needed.

get_geodataframe('vector.shp', geom=self.region)

### Current behaviour

Errors in gis_utils.bbox_from_file_and_filters
At the line where read_info(fn), fn is of type fsspec.implementations.local.LocalFileOpener
Note that it works if I convert my shapefile to a geojson file or if for my shapefile I use read_info(fn.path) instead of read_info(fn)

```
File "C:\Users\boisgont\D\Repos\hydromt\hydromt_wflow\hydromt_wflow\wflow.py", line 481, in setup_rivers
    gdf_riv = self.data_catalog.get_geodataframe(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\data_catalog.py", line 1480, in get_geodataframe
    gdf = source.get_data(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\data_adapter\geodataframe.py", line 250, in get_data
    gdf = self._read_data(fns, bbox, geom, buffer, predicate, logger=logger)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\data_adapter\geodataframe.py", line 295, in _read_data
    gdf = io.open_vector(
          ^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\io.py", line 637, in open_vector
    gdf = _read(f)
          ^^^^^^^^
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\io.py", line 621, in _read
    bbox_reader = gis_utils.bbox_from_file_and_filters(f, bbox, geom, crs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\gis_utils.py", line 602, in bbox_from_file_and_filters
    source_crs = CRS(read_info(fn).get("crs", "EPSG:4326"))  # assume WGS84
                     ^^^^^^^^^^^^^
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-wflow\Lib\site-packages\pyogrio\core.py", line 261, in read_info
    result = ogr_read_info(
             ^^^^^^^^^^^^^^
  File "pyogrio\\_io.pyx", line 1512, in pyogrio._io.ogr_read_info
  File "pyogrio\\_io.pyx", line 167, in pyogrio._io.ogr_open
pyogrio.errors.DataSourceError: '/vsimem/f2c5d466645c4bd5979d57e368e79fab' not recognized as a supported file format. It might help to specify the correct driver explicitly by prefixing the file path with '<DRIVER>:', e.g. 'CSV:path'.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-wflow\Scripts\hydromt.exe\__main__.py", line 7, in <module>
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-wflow\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-wflow\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-wflow\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-wflow\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-wflow\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-wflow\Lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\cli\main.py", line 221, in build
    mod.build(region, opt=opt)
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\models\model_api.py", line 236, in build
    self._run_log_method(method, **kwargs)
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\models\model_api.py", line 178, in _run_log_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt_wflow\hydromt_wflow\wflow.py", line 481, in setup_rivers
    gdf_riv = self.data_catalog.get_geodataframe(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\data_catalog.py", line 1480, in get_geodataframe
    gdf = source.get_data(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\data_adapter\geodataframe.py", line 250, in get_data
    gdf = self._read_data(fns, bbox, geom, buffer, predicate, logger=logger)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\data_adapter\geodataframe.py", line 295, in _read_data
    gdf = io.open_vector(
          ^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\io.py", line 637, in open_vector
    gdf = _read(f)
          ^^^^^^^^
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\io.py", line 621, in _read
    bbox_reader = gis_utils.bbox_from_file_and_filters(f, bbox, geom, crs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\boisgont\D\Repos\hydromt\hydromt\hydromt\gis_utils.py", line 602, in bbox_from_file_and_filters
    source_crs = CRS(read_info(fn).get("crs", "EPSG:4326"))  # assume WGS84
                     ^^^^^^^^^^^^^
  File "C:\Users\boisgont\Miniconda3\envs\hydromt-wflow\Lib\site-packages\pyogrio\core.py", line 261, in read_info
    result = ogr_read_info(
             ^^^^^^^^^^^^^^
  File "pyogrio\\_io.pyx", line 1512, in pyogrio._io.ogr_read_info
  File "pyogrio\\_io.pyx", line 167, in pyogrio._io.ogr_open
pyogrio.errors.DataSourceError: '/vsimem/f2c5d466645c4bd5979d57e368e79fab' not recognized as a supported file format. It might help to specify the correct driver explicitly by prefixing the file path with '<DRIVER>:', e.g. 'CSV:path'.
```

### Desired behaviour

Shapefiles should be supported

### Additional context

I guess we can do a try/except or if hasattr(fn, path) and in use fn.path instead. Not sure if the problem only happens for shapefiles or other filetype as well.

**Comment by hboisgon** [comment]
Additionally I see this (line 602 in bbox_from_file_and_filters):

`source_crs = CRS(read_info(fn).get("crs", "EPSG:4326"))  # assume WGS84`

If a CRS is not encoded in the file, the user can specify CRS in the data catalog. If the user did provide it, this should be the default first before 4326 is assumed.

**Comment by DirkEilander** [comment]
Would it be logical to create separate drivers for 1) `geopandas.read_file` (based on fiona), 2) `pyogrio.read_dataframe`, and 3) `hydromt.io.open_vector_from_table`? That would largely simplify this method I think, e.g. the bbox_from_file_and_filters method is only strictly required for 2) right? And 1) does not have to be functional for cloud based vector data if we also have 2). See also discussion in #525  

1) and 3) where merged before to be used in the `hydromt.io.open_geodataset` method for which we would than need to fine an alternative solution. See also discussion in #372

**Comment by hboisgon** [comment]
Agreed that separate drivers make sense. One thing is that the problem also came yesterday when building a model using region = {'geom': 'path/to/region.shp'}. So we need to carefully choose the driver or handle the geom passed here.

**Comment by hboisgon** [comment]
I see this warning now so I actually think this should be solved by passing fn.path rather than fn is fn has path attribute:

```pyogrio\core.py:261: RuntimeWarning: File /vsimem/70a3aa9d61d945d593495fa05fc827ee has GPKG application_id, but non conformant file extension```

So what I think happens is maybe with fn it still works for geopackage and geojson files but not enough for shapefiles. To get this try open_geodataframe() for hydro_lakes or hydro_reservoirs in artifact_data or deltares_data
